import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StyledEngineProvider } from '@mui/material/styles';
import { ThemeProvider } from "@/context/themeProvider";
import ThemeWrapper from '@/components/common/themeWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <StyledEngineProvider injectFirst>
            <ThemeProvider>
              <ThemeWrapper>
                {children}
              </ThemeWrapper>
            </ThemeProvider>
          </StyledEngineProvider>
        </body>
    </html>
  );
}
